name = input("Enter your name: ")
age = int(input("Enter your age: "))
print(f"Name: {name}, Age: {age}")

s = input("Enter string: ")
i = int(input("Enter integer: "))
f = float(input("Enter float: "))
print("String:", s)
print("Integer:", i)
print("Float:", f)